config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # the index of the post will be the root, this is in the controller
  root 'posts#index', as: 'home'

  # route to the about page
  get 'about' => 'pages#about', as: 'about'

  # change post to resource
  # this gives you access to a lot of premade HTTP methods
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    # this is saying that a post can have many comments
  has_many :comments
    validates :title, presence: true,
    length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "Carlos", password: "1234", only: [:destroy]

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        # this sets variables that will be used in the view
        @title = 'About Us'
        @content = "This is the about page"
    end
end

app/controllers/posts_controller.rb
# handles everything in the /posts/ route
class PostsController < ApplicationController
    http_basic_authenticate_with name: "Carlos", password: "1234", except: [:index, :show]
    # this would be the root "posts/" route
    def index
        # this will display all of the posts on index page
        @posts = Post.all
    end

    # this will find the post id to display
    def show
        @post = Post.find(params[:id])
    end

    # this will take care of the form
    # "/posts/new"
    def new
        @post = Post.new
    end

    # this will create a new post
    def create
        # this returns an object with the title and the body that was submitted through the form post
        # render plain: params[:post].inspect
        # this step creates a new post with the post params
        @post = Post.new(post_params)
        # this step saves the post
        if(@post.save)
            # this step will load the show view that will display the post
            redirect_to @post
        else
            render 'new'
        end
    end

    # this will handle the edit action
    def edit
        @post = Post.find(params[:id])
    end

    # this will handle submitting a new edit
    def update
        @post = Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    # this will handle deleting a post
    def destroy
        # find the post by id
        @post = Post.find(params[:id])
        # delete the post
        @post.destroy
        # redirect to the path that has all the remaining posts
        redirect_to posts_path
    end

    # this method will define what a post will look like
    private def post_params
        # here we grab the post object and shove the title and body attribute into it
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Commments</h3>
<% @post.comments.each do |comment| %>
    <div class="card mb-3">
        <div class="card-body">
            <p><strong><%= comment.username %></strong>: <%= comment.body %>
            <%= link_to '[x]', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?'} %></p>
        </div>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_field(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-default'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%# meta tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%# styled sheet and JS %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-default bg-light">
  <a class="navbar-brand" href="#">Simple Blog</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li><%= link_to "Home", home_path %></li>
    </ul>
    <ul class="navbar-nav mr-auto navbar-right">
      <li><%= link_to "Create Post", new_post_path %></li>
    </ul>
  </div>
</nav>

<div class="container">
  <%# this yield is where everything will be output from %>
    <%= yield %>
</div>
  </body>
</html>

app/views/pages/about.html.erb
<%# syntax for adding variables, this comes from the controllers/pages_controller.rb file %>
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%# form_for is a helper %>
<%# this will submit to our create method %>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <!-- Check for errors -->
	<% if @post.errors.any? %>
	    <% @post.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>
<p>
<%# the f comes from line 3 %>
<%# label will be what the p tag renders %>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :body %><br>
    <%= f.text_area( :body, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<%# only use equal sign if your outputting a variable %>

<!-- this code is saying "for each post, render a title and body -->
<% @posts.each do |post| %>
    <div class="card mb-4">
        <div class="card-title p-3">
        <h3><%= post.title %></h3>
        </div>
        <div class="card-body p-3">
        <p><%= post.body %></p>
        </div>
        <%= link_to "Read More", post_path(post), :class => "btn btn-default"%>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%# form_for is a helper %>
<%# this will submit to our create method %>
<%= form_for :post, url: posts_path do |f| %>
<p>
<%# the f comes from line 3 %>
<%# label will be what the p tag renders %>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :body %><br>
    <%= f.text_area( :body, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default'%>
<%= link_to "Delete", post_path(@post),
                method: :delete,
                data: {confirm: 'Are you sure?'},
                :class => 'btn btn-danger'%>
<hr>

<%# these are located in the comments folder %>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>
